# Generated by Django 4.2.8 on 2024-04-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Property')),
                ('category', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'seller')], max_length=20, verbose_name='Buyer/Seller')),
                ('flex_organic', models.CharField(choices=[('Flex', 'Flex'), ('Organic', 'Organic')], max_length=20, verbose_name='Flex/Organic')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('closing_date', models.DateField(null=True, verbose_name='Closing date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Sale Price')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission')),
                ('mls_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='MLS Fee')),
                ('loop_closed', models.BooleanField(default=False, verbose_name='Loop Closed')),
                ('notion_closed', models.BooleanField(default=False, verbose_name='Notion closed')),
                ('flex_closed', models.BooleanField(default=False, verbose_name='Flex Tracker Updated')),
                ('zillow_closed', models.BooleanField(default=False, verbose_name='Zillow Closed')),
                ('kyn', models.BooleanField(default=False, verbose_name='Know Your Numbers Updated')),
                ('close_pending', models.BooleanField(default=False, verbose_name='MVT Close and Pending Updated')),
                ('notion', models.BooleanField(default=False, verbose_name='Notion')),
                ('congratulations', models.BooleanField(default=False, verbose_name='Congrats Email')),
                ('calendar', models.BooleanField(default=False, verbose_name='Calendar Invites')),
                ('flex_tracker', models.BooleanField(default=False, verbose_name='Flex Tracker')),
                ('loop', models.BooleanField(default=False, verbose_name='Loop Created')),
                ('da_requested', models.BooleanField(default=False, verbose_name='DA requested')),
                ('completed', models.BooleanField(verbose_name='Completado')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed Deal')),
            ],
        ),
    ]
