# Generated by Django 4.2.8 on 2024-04-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='undercontract',
            name='zillow_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Zillow Commission'),
            preserve_default=False,
        ),
    ]
