# Generated by Django 4.2.8 on 2024-04-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0002_undercontract_zillow_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='undercontract',
            name='Zillow_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Zillow Payment'),
            preserve_default=False,
        ),
    ]
