# Generated by Django 4.2.8 on 2024-04-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0003_undercontract_zillow_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='undercontract',
            old_name='Zillow_payment',
            new_name='zillow_payment',
        ),
    ]
