# Generated by Django 4.2.8 on 2024-04-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0004_rename_zillow_payment_undercontract_zillow_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undercontract',
            name='zillow_payment',
        ),
    ]
