# Generated by Django 4.2.8 on 2024-04-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0006_undercontract_zillow_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undercontract',
            name='zillow_commission',
        ),
        migrations.RemoveField(
            model_name='undercontract',
            name='zillow_payment',
        ),
    ]
