# Generated by Django 4.2.8 on 2024-04-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0007_remove_undercontract_zillow_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='undercontract',
            name='escrow',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Escrow'),
            preserve_default=False,
        ),
    ]
