# Generated by Django 4.2.8 on 2024-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0008_undercontract_escrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undercontract',
            name='flex_organic',
            field=models.CharField(choices=[('Flex', 'Flex'), ('Team Lead', 'Team Lead'), ('Organic', 'Organic')], max_length=20, verbose_name='Flex/Organic'),
        ),
    ]
